Add option --daemon to use daemonize

diff --git a/sbin/debuilder b/sbin/debuilder
--- a/sbin/debuilder
+++ b/sbin/debuilder
@@ -28,6 +28,16 @@ debuilder_on_exit()
     exit $exitval
 }
 
+if [ $# -eq 1 ]; then
+    if [ "$1" = "--daemon" ]; then
+        daemon --noconfig --name='debuilder' -- debuilder
+        exit 0
+    fi
+    echo "debuilder: error: unexpected argument '$1'" >&2
+    exit 1
+fi
+
+
 # Get essential directory paths defined at installation time:
 # DEBUILDER_CONFDIR and DEBUILDER_LIBDIR.
 . debuilder-installdirs
